### PR TITLE
Introduce customisable decorators for custom layout & styling

### LINKED ISSUE #8: Shift to alternative CSS approach
Styling for each chapter and section is using React inline styles and if a story has many many chapters and sections it may cause a performance hit.  React inline styles are [not the best way](https://byjoeybaker.com/react-inline-styles) to handling styling anyways.

### PR DESCRIPTION
**Pull request by mfal**
This one resolves #8

### CODE REVIEW

**Comment by mfal** [comment]
Hey @yangshun, what do you think about this approach? Should I go further with the README?

**Comment by yangshun** [comment]
Hey @mfal  thanks for the PR! I haven't had time to look into it yet, but I'll do so within the next few days, I promise.

Just curious, did this PR stem from a real world problem you faced, if so, could you point me to the project if it's open sourced?

**Comment by mfal** [comment]
Yes, but unfortunately it's not public. But the problem is quite simple:

With your Addon we can use Storybook as a living style guide. Unfortunately there is no way to change the rendering of the output (used classes, structure) and thus make the designers happy ;-)

**Comment by yangshun** [comment]
Thanks loads!

**Comment by aronstrandberg** [comment]
@yangshun forgive me if I'm doing something wrong, or have these changes not been published to `npm`? Would be very helpful if you could publish them if so!

**Comment by yangshun** [comment]
@aronstrandberg I haven't published them because there's no documentation for them at the moment. Could you install the new version via Git commit hash for the time being?

**Pull request merged**
